# -*- coding: utf-8 -*-
"""NTI Decision tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYJ0b8M3IZ_xRZ25c5ZfZS-1v4455gPx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv("diabetes.csv")

print(data.info())

print(data["Outcome"].value_counts())
print("Percentage\n")
print(data["Outcome"].value_counts(normalize=True)*100)

data.describe()

zero_cols = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
for col in zero_cols:
    zeros = (data[col]==0).sum()
    perc = zeros/len(data) * 100
    print(f"{col:25s} : {zeros:3d} zeros, {perc:0.2f}%")
#

plt.figure(figsize=(6, 4))
data['Outcome'].value_counts().plot(kind='bar', color=["#067D57", '#D85A30'], edgecolor='Grey')
plt.title('Class Distribution: Diabetes vs No Diabetes')
plt.xticks([0, 1], ['No Diabetes (0)', 'Diabetes (1)'], rotation=0)
plt.ylabel('Count')
plt.tight_layout()
plt.show()

